name: bonzenbunker.com
favicon: null
layout_spectrum: 0.99391
typography_spectrum: 0.4401
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b6b8b7'
    - '#ffffff'
    - '#cccccc'
    - '#e8e8e8'
    - '#d7d7d7'
  brandStrength: 0
  lightness: 1
  saturation: 0.31610391894355416
  rhythmicContrast: 1
purpose: []
