name: bonzenbunker.com
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4401
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: bonzenbunker.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b6b8b7'
    - '#ffffff'
    - '#cccccc'
    - '#e8e8e8'
    - '#d7d7d7'
  brandStrength: 0
  lightness: 1
  saturation: 0.3161039189435542
  rhythmicContrast: 1
purpose: []
